Fix missing-prototypes
uptime.c:46:8: error: no previous prototype for 'read_uptime' [-Werror=missing-prototypes]
cpu.c:54:8: error: no previous prototype for 'read_cpuload' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>